
const actionTypes = {
    TOGGLE_THEME: 'TOGGLE_THEME',
    USER_LOGIN: 'USER_LOGIN',
    USER_LOGOUT: 'USER_LOGOUT',
    SET_PENDING_FAV: 'SET_PENDING_FAV',
    REMOVE_PENDING_FAV: 'REMOVE_PENDING_FAV',
    UPDATE_FAVORITES: 'UPDATE_FAVORITES',
};

export default actionTypes;
